var chem = {
   "type": "FeatureCollection",
   "features": [
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 36.4849,35.6599 ]
    },
    "properties": {
    "data_id":6081850,
    "iso":760,
    "event_id_cnty":"SYR61160",
    "event_id_no_cnty":61160,
    "event_date":"24 May 2019",
    "year":2019,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Chemical weapon",
    "actor1":"Military Forces of Syria (2000-)",
    "assoc_actor_1":"Allied Syrian and/or Russian Forces",
    "inter1":1,
    "actor2":"",
    "assoc_actor_2":"",
    "inter2":0,
    "interaction":10,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Idleb",
    "admin2":"Ariha",
    "admin3":"Ehsem",
    "location":"Kansafra",
    "geo_precision":1,
    "source":"Liveuamap",
    "source_scale":"Local partner-New media",
    "notes":"On 24 May 2019, regime ground forces fired artillery and Syrian and/or Russian warplanes carried out air raids that produced a yellow cloud that appeared to be chlorine on the town of Kansafra. Neither injuries nor fatalities reported.",
    "fatalities":0,
    "timestamp":1571164584,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 37.1175,36.2294 ]
    },
    "properties": {
    "data_id":6044345,
    "iso":760,
    "event_id_cnty":"SYR49229",
    "event_id_no_cnty":49229,
    "event_date":"24 November 2018",
    "year":2018,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Chemical weapon",
    "actor1":"Unidentified Armed Group (Syria)",
    "assoc_actor_1":"",
    "inter1":3,
    "actor2":"Civilians (Syria)",
    "assoc_actor_2":"",
    "inter2":7,
    "interaction":37,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Aleppo",
    "admin2":"Jebel Saman",
    "admin3":"Jebel Saman",
    "location":"Aleppo - Al-Khaldiya",
    "geo_precision":1,
    "source":"Liveuamap; SOHR",
    "source_scale":"Local partner-New media",
    "notes":"Unidentified armed fighters shelled the al-Khaldiya and al-Zahraa neighborhoods of Aleppo city which caused at least 94 cases of suffocation among civilians. No fatalities were reported.",
    "fatalities":0,
    "timestamp":1571164397,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 37.0982,36.2232 ]
    },
    "properties": {
    "data_id":6044346,
    "iso":760,
    "event_id_cnty":"SYR49235",
    "event_id_no_cnty":49235,
    "event_date":"24 November 2018",
    "year":2018,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Chemical weapon",
    "actor1":"Unidentified Armed Group (Syria)",
    "assoc_actor_1":"",
    "inter1":3,
    "actor2":"Civilians (Syria)",
    "assoc_actor_2":"",
    "inter2":7,
    "interaction":37,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Aleppo",
    "admin2":"Jebel Saman",
    "admin3":"Jebel Saman",
    "location":"Aleppo - Al-Zahraa",
    "geo_precision":1,
    "source":"SOHR; Liveuamap",
    "source_scale":"Local partner-New media",
    "notes":"Unidentified armed fighters shelled the al-Khaldiya and al-Zahraa neighborhoods of Aleppo city which caused at least 94 cases of suffocation among civilians. No fatalities were reported.",
    "fatalities":0,
    "timestamp":1571164397,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 36.4046,33.5706 ]
    },
    "properties": {
    "data_id":6041036,
    "iso":760,
    "event_id_cnty":"SYR31140",
    "event_id_no_cnty":31140,
    "event_date":"07 April 2018",
    "year":2018,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Chemical weapon",
    "actor1":"Military Forces of Syria (2000-)",
    "assoc_actor_1":"Military Forces of Syria (2000-) Syrian Arab Air Force; Allied Syrian and/or Russian Forces",
    "inter1":1,
    "actor2":"Civilians (Syria)",
    "assoc_actor_2":"",
    "inter2":7,
    "interaction":17,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Rural Damascus",
    "admin2":"Duma",
    "admin3":"Duma",
    "location":"Duma",
    "geo_precision":1,
    "source":"SHAM; Liveuamap; SNHR; Undisclosed Source; SOHR",
    "source_scale":"Local partner-Other",
    "notes":"Regime forces fired hundreds of artillery shells and missiles while regime helicopters dropped at least 25 barrel bombs and Syrian or Russian warplanes carried out at least 50 raids on the town of Duma, killing at least 40 and injuring between 119 and 304 more. At least 11 civilians were injured when warplanes bombed a building which collapsed on the basement where they had been hiding. In addition, at least 43 were killed and 186 injured after being targeted with toxic gas by regime forces. A conflicting source indicates as many as 1,000 people suffered suffocation symptoms from toxic gas in the city.",
    "fatalities":83,
    "timestamp":1571164393,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 36.4409,33.5583 ]
    },
    "properties": {
    "data_id":6131072,
    "iso":760,
    "event_id_cnty":"SYR42835",
    "event_id_no_cnty":42835,
    "event_date":"26 March 2018",
    "year":2018,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Chemical weapon",
    "actor1":"Military Forces of Syria (2000-)",
    "assoc_actor_1":"",
    "inter1":1,
    "actor2":"Civilians (Syria)",
    "assoc_actor_2":"",
    "inter2":7,
    "interaction":17,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Rural Damascus",
    "admin2":"Duma",
    "admin3":"Duma",
    "location":"Shafuniyeh",
    "geo_precision":1,
    "source":"Undisclosed Source",
    "source_scale":"Local partner-Other",
    "notes":"Regime forces shelled al-Shifunya town with suspected use of toxic gas, leaving 2 people dead and at least 17 injured.",
    "fatalities":2,
    "timestamp":1571164647,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 36.3524,33.5284 ]
    },
    "properties": {
    "data_id":6040817,
    "iso":760,
    "event_id_cnty":"SYR30292",
    "event_id_no_cnty":30292,
    "event_date":"21 March 2018",
    "year":2018,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Chemical weapon",
    "actor1":"Military Forces of Syria (2000-)",
    "assoc_actor_1":"Allied Syrian and/or Russian Forces",
    "inter1":1,
    "actor2":"",
    "assoc_actor_2":"",
    "inter2":0,
    "interaction":10,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Rural Damascus",
    "admin2":"Rural Damascus",
    "admin3":"Arbin",
    "location":"Zamalka",
    "geo_precision":1,
    "source":"Undisclosed Source; SOHR; SHAM",
    "source_scale":"Local partner-Other",
    "notes":"Regime forces fired rocket shells as warplanes carried out dozens of strikes on Zamalka town in the Eastern Ghouta, reportedly also using incendiary weapons and chemical gases. No fatalities reported.",
    "fatalities":0,
    "timestamp":1571164392,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 36.4046,33.5706 ]
    },
    "properties": {
    "data_id":6040754,
    "iso":760,
    "event_id_cnty":"SYR30052",
    "event_id_no_cnty":30052,
    "event_date":"18 March 2018",
    "year":2018,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Chemical weapon",
    "actor1":"Military Forces of Syria (2000-)",
    "assoc_actor_1":"Military Forces of Syria (2000-) Syrian Arab Air Force; Military Forces of Russia (2000-)",
    "inter1":1,
    "actor2":"Civilians (Syria)",
    "assoc_actor_2":"",
    "inter2":7,
    "interaction":17,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Rural Damascus",
    "admin2":"Duma",
    "admin3":"Duma",
    "location":"Duma",
    "geo_precision":1,
    "source":"SNHR; Liveuamap; SHAM; SOHR; Airwars",
    "source_scale":"Local partner-Other",
    "notes":"Regime forces fired artillery and rocket shells while regime helicopters dropped barrel bombs and Russian warplanes carried out more than 17 raids on the Jaysh al-Islam-controlled city of Duma which killed between 5 to 13 civilians and injured between 10 to 20 others. There were reports that chlorine gas was used in the attacks on the city.",
    "fatalities":5,
    "timestamp":1571164392,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 36.3524,33.5284 ]
    },
    "properties": {
    "data_id":6040710,
    "iso":760,
    "event_id_cnty":"SYR29906",
    "event_id_no_cnty":29906,
    "event_date":"15 March 2018",
    "year":2018,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Chemical weapon",
    "actor1":"Military Forces of Syria (2000-)",
    "assoc_actor_1":"Military Forces of Russia (2000-)",
    "inter1":1,
    "actor2":"Civilians (Syria)",
    "assoc_actor_2":"",
    "inter2":7,
    "interaction":17,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Rural Damascus",
    "admin2":"Rural Damascus",
    "admin3":"Arbin",
    "location":"Zamalka",
    "geo_precision":1,
    "source":"SNHR; Undisclosed Source; SHAM; SOHR; Airwars",
    "source_scale":"Local partner-Other",
    "notes":"Russian warplanes carried out raids on Zamalka while regime forces fired rocket shells at the town. Reports claimed that chemical weapons and napalm bombs were used in the attacks. It was reported that 19 civilians were killed and 20 were injured.",
    "fatalities":19,
    "timestamp":1571164392,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 36.3836,33.5283 ]
    },
    "properties": {
    "data_id":6040479,
    "iso":760,
    "event_id_cnty":"SYR29251",
    "event_id_no_cnty":29251,
    "event_date":"07 March 2018",
    "year":2018,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Chemical weapon",
    "actor1":"Military Forces of Syria (2000-) Syrian Arab Air Force",
    "assoc_actor_1":"Military Forces of Russia (2000-)",
    "inter1":1,
    "actor2":"Civilians (Syria)",
    "assoc_actor_2":"",
    "inter2":7,
    "interaction":17,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Rural Damascus",
    "admin2":"Rural Damascus",
    "admin3":"Arbin",
    "location":"Hamouriya",
    "geo_precision":1,
    "source":"SOHR; SNHR; Liveuamap; Airwars; SHAM",
    "source_scale":"Local partner-Other",
    "notes":"Russian warplanes and regime helicopters carried out strikes on the town of Hamouriya which killed 26 civilians with reports of civilians experiencing suffocation symptoms from a gas attack.",
    "fatalities":26,
    "timestamp":1571164392,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 36.3841,33.5181 ]
    },
    "properties": {
    "data_id":6040500,
    "iso":760,
    "event_id_cnty":"SYR29287",
    "event_id_no_cnty":29287,
    "event_date":"07 March 2018",
    "year":2018,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Chemical weapon",
    "actor1":"Military Forces of Syria (2000-)",
    "assoc_actor_1":"Military Forces of Syria (2000-) Syrian Arab Air Force; Military Forces of Russia (2000-)",
    "inter1":1,
    "actor2":"Civilians (Syria)",
    "assoc_actor_2":"",
    "inter2":7,
    "interaction":17,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Rural Damascus",
    "admin2":"Rural Damascus",
    "admin3":"Kafr Batna",
    "location":"Saqba",
    "geo_precision":1,
    "source":"SOHR; SHAM; Undisclosed Source; Liveuamap; Airwars; SNHR",
    "source_scale":"Local partner-Other",
    "notes":"Russian warplanes carried out a raid on Saqba which killed 19 civilians and injured 100 others with reports of civilians experiencing suffocation symptoms from a gas attack. In addition, regime forces fired ground-to-ground missiles at the town while regime helicopters carried out strikes.",
    "fatalities":19,
    "timestamp":1571164392,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 36.3836,33.5283 ]
    },
    "properties": {
    "data_id":6040424,
    "iso":760,
    "event_id_cnty":"SYR29121",
    "event_id_no_cnty":29121,
    "event_date":"05 March 2018",
    "year":2018,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Chemical weapon",
    "actor1":"Military Forces of Syria (2000-)",
    "assoc_actor_1":"Military Forces of Syria (2000-) Syrian Arab Air Force; Allied Syrian and/or Russian Forces",
    "inter1":1,
    "actor2":"Civilians (Syria)",
    "assoc_actor_2":"",
    "inter2":7,
    "interaction":17,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Rural Damascus",
    "admin2":"Rural Damascus",
    "admin3":"Arbin",
    "location":"Hamouriya",
    "geo_precision":1,
    "source":"Undisclosed Source; Liveuamap; SNHR; SOHR; SHAM; Airwars",
    "source_scale":"Local partner-Other",
    "notes":"The Syrian army shelled Hamouriya town in Rural Damascus in conjunction with regime and/or Russian airstrikes and a barrel bomb bombardment by Syrian helicopters. As a result, 26 civilians were killed and 18 cases of suffocation symptoms and shortness of breath were reported.",
    "fatalities":26,
    "timestamp":1571164392,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 36.4409,33.5583 ]
    },
    "properties": {
    "data_id":6125228,
    "iso":760,
    "event_id_cnty":"SYR55435",
    "event_id_no_cnty":55435,
    "event_date":"26 February 2018",
    "year":2018,
    "time_precision":2,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Chemical weapon",
    "actor1":"Allied Syrian and/or Russian Forces",
    "assoc_actor_1":"",
    "inter1":1,
    "actor2":"Civilians (Syria)",
    "assoc_actor_2":"",
    "inter2":7,
    "interaction":17,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Rural Damascus",
    "admin2":"Duma",
    "admin3":"Duma",
    "location":"Shafuniyeh",
    "geo_precision":1,
    "source":"SNHR",
    "source_scale":"Local partner-Other",
    "notes":"On March 1st, 1 civilian succumbed to the injuries he sustained a few days prior when Syrian and/or Russian warplanes carried out airstrikes on Shafuniyeh using chlorine gas.",
    "fatalities":1,
    "timestamp":1571164640,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 36.5992,36.5016 ]
    },
    "properties": {
    "data_id":5866950,
    "iso":760,
    "event_id_cnty":"SYR21717",
    "event_id_no_cnty":21717,
    "event_date":"16 February 2018",
    "year":2018,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Chemical weapon",
    "actor1":"Military Forces of Turkey (2016-)",
    "assoc_actor_1":"Operation Olive Branch",
    "inter1":8,
    "actor2":"Civilians (Syria)",
    "assoc_actor_2":"",
    "inter2":7,
    "interaction":78,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Aleppo",
    "admin2":"Afrin",
    "admin3":"Sheikh El-Hadid",
    "location":"Sheikh al-Hadid",
    "geo_precision":2,
    "source":"SOHR",
    "source_scale":"Other",
    "notes":"Turkish and Olive Branch faction forces shells the Sheik al-Hadid area of western Afrin, injuring 6 people as Turkish warplanes targeted the area. The use of gasses in shelling was reported by medical personnel, with victims exhibiting pupil dilation and difficulty breathing. No fatalities reported.",
    "fatalities":0,
    "timestamp":1567462278,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 36.8891,36.7335 ]
    },
    "properties": {
    "data_id":6075857,
    "iso":760,
    "event_id_cnty":"SYR20966",
    "event_id_no_cnty":20966,
    "event_date":"06 February 2018",
    "year":2018,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Chemical weapon",
    "actor1":"YPG: Peoples Protection Units",
    "assoc_actor_1":"",
    "inter1":2,
    "actor2":"Operation Olive Branch",
    "assoc_actor_2":"JSH: Free Syrian Army",
    "inter2":2,
    "interaction":22,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Aleppo",
    "admin2":"Afrin",
    "admin3":"Bulbul",
    "location":"Sheikh Khoraz",
    "geo_precision":2,
    "source":"Liveuamap",
    "source_scale":"Local partner-New media",
    "notes":"YPG fighters fired a shell on Olive Branch FSA faction positions near Sheikh Khoraz in northern Afrin, injuring around 20 faction fighters. The factions accused YPG of using a shell with chlorine gas, a charge the group and other sources deny. The YPG claimed Turkish forces launched the chemical attack on its own FSA allies. No fatalities reported.",
    "fatalities":0,
    "timestamp":1571164569,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 36.8061,35.8611 ]
    },
    "properties": {
    "data_id":6043036,
    "iso":760,
    "event_id_cnty":"SYR42605",
    "event_id_no_cnty":42605,
    "event_date":"04 February 2018",
    "year":2018,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Chemical weapon",
    "actor1":"Military Forces of Syria (2000-)",
    "assoc_actor_1":"",
    "inter1":1,
    "actor2":"Civilians (Syria)",
    "assoc_actor_2":"",
    "inter2":7,
    "interaction":17,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Idleb",
    "admin2":"Idleb",
    "admin3":"Saraqab",
    "location":"Saraqab",
    "geo_precision":2,
    "source":"Undisclosed Source; Liveuamap",
    "source_scale":"Local partner-Other",
    "notes":"Regime forces shelled Saraqab town with toxic gas, injuring 11 civilians. No fatalities were reported.",
    "fatalities":0,
    "timestamp":1571164395,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 36.4046,33.5706 ]
    },
    "properties": {
    "data_id":6038710,
    "iso":760,
    "event_id_cnty":"SYR20509",
    "event_id_no_cnty":20509,
    "event_date":"01 February 2018",
    "year":2018,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Chemical weapon",
    "actor1":"Military Forces of Syria (2000-)",
    "assoc_actor_1":"Allied Syrian and/or Russian Forces",
    "inter1":1,
    "actor2":"Civilians (Syria)",
    "assoc_actor_2":"",
    "inter2":7,
    "interaction":17,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Rural Damascus",
    "admin2":"Duma",
    "admin3":"Duma",
    "location":"Duma",
    "geo_precision":1,
    "source":"SHAM; SNHR",
    "source_scale":"Local partner-Other",
    "notes":"Warplanes carried out strikes as the Syrian army shelled Duma city in Rural Damascus, using chemical weapons and artillery which led to the killing of 2 civilians and the injury of several others, in addition to several cases of suffocation symptoms among the civilians.",
    "fatalities":2,
    "timestamp":1571164389,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 36.4046,33.5706 ]
    },
    "properties": {
    "data_id":6075475,
    "iso":760,
    "event_id_cnty":"SYR20415",
    "event_id_no_cnty":20415,
    "event_date":"31 January 2018",
    "year":2018,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Chemical weapon",
    "actor1":"Military Forces of Syria (2000-)",
    "assoc_actor_1":"",
    "inter1":1,
    "actor2":"Civilians (Syria)",
    "assoc_actor_2":"",
    "inter2":7,
    "interaction":17,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Rural Damascus",
    "admin2":"Duma",
    "admin3":"Duma",
    "location":"Duma",
    "geo_precision":1,
    "source":"Liveuamap",
    "source_scale":"Local partner-New media",
    "notes":"Regime forces launched artillery, allegedly tipped with chlorine, at the town of Duma with cases of suffocation symptoms among civilians in the city. No fatalities reported.",
    "fatalities":0,
    "timestamp":1571164569,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 36.4046,33.5706 ]
    },
    "properties": {
    "data_id":6038450,
    "iso":760,
    "event_id_cnty":"SYR19670",
    "event_id_no_cnty":19670,
    "event_date":"22 January 2018",
    "year":2018,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Chemical weapon",
    "actor1":"Military Forces of Syria (2000-)",
    "assoc_actor_1":"",
    "inter1":1,
    "actor2":"Civilians (Syria)",
    "assoc_actor_2":"",
    "inter2":7,
    "interaction":17,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Rural Damascus",
    "admin2":"Duma",
    "admin3":"Duma",
    "location":"Duma",
    "geo_precision":1,
    "source":"SHAM; SOHR; SNHR",
    "source_scale":"Local partner-Other",
    "notes":"Regime forces fired chlorine-tipped shells at the town of Duma which resulted in at least 20 cases of suffocation symptoms among civilians. In addition, regime forces shelled the town with artillery, rockets, and ground-to-ground missiles, killing 1 male civilian.",
    "fatalities":1,
    "timestamp":1571164389,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 36.4046,33.5706 ]
    },
    "properties": {
    "data_id":6038431,
    "iso":760,
    "event_id_cnty":"SYR19604",
    "event_id_no_cnty":19604,
    "event_date":"21 January 2018",
    "year":2018,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Chemical weapon",
    "actor1":"Military Forces of Syria (2000-)",
    "assoc_actor_1":"",
    "inter1":1,
    "actor2":"Civilians (Syria)",
    "assoc_actor_2":"",
    "inter2":7,
    "interaction":17,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Rural Damascus",
    "admin2":"Duma",
    "admin3":"Duma",
    "location":"Duma",
    "geo_precision":1,
    "source":"SNHR; Liveuamap; SOHR; SHAM",
    "source_scale":"Local partner-Other",
    "notes":"Military Forces of Syria shelled Duma in Rural Damascus, allegedly with chlorine-tipped shells, killing 4 civilians and injuring at least 13.",
    "fatalities":4,
    "timestamp":1571164389,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 36.4046,33.5706 ]
    },
    "properties": {
    "data_id":5843011,
    "iso":760,
    "event_id_cnty":"SYR18928",
    "event_id_no_cnty":18928,
    "event_date":"13 January 2018",
    "year":2018,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Chemical weapon",
    "actor1":"Military Forces of Syria (2000-)",
    "assoc_actor_1":"",
    "inter1":1,
    "actor2":"Civilians (Syria)",
    "assoc_actor_2":"",
    "inter2":7,
    "interaction":17,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Rural Damascus",
    "admin2":"Duma",
    "admin3":"Duma",
    "location":"Duma",
    "geo_precision":2,
    "source":"SHAM",
    "source_scale":"National",
    "notes":"Regime forces targeted the international highway adjacent to Duma with chemical weapons which caused breathing trouble for several citizens who were taken to local field hospitals. No fatalities reported.",
    "fatalities":0,
    "timestamp":1567462248,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 36.4046,33.5706 ]
    },
    "properties": {
    "data_id":6130792,
    "iso":760,
    "event_id_cnty":"SYR42426",
    "event_id_no_cnty":42426,
    "event_date":"13 January 2018",
    "year":2018,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Chemical weapon",
    "actor1":"Military Forces of Syria (2000-)",
    "assoc_actor_1":"",
    "inter1":1,
    "actor2":"Civilians (Syria)",
    "assoc_actor_2":"",
    "inter2":7,
    "interaction":17,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Rural Damascus",
    "admin2":"Duma",
    "admin3":"Duma",
    "location":"Duma",
    "geo_precision":1,
    "source":"Undisclosed Source",
    "source_scale":"Local partner-Other",
    "notes":"Syrian regime forces targeted with 51 artillery shells and seven surface to surface missiles loaded with toxic gas civilian areas and houses in Duma city in Rural Damascus, which killed two civilians including one child, and injured 19 civilians including two children.",
    "fatalities":2,
    "timestamp":1571164647,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 36.4005,33.5503 ]
    },
    "properties": {
    "data_id":6042267,
    "iso":760,
    "event_id_cnty":"SYR39223",
    "event_id_no_cnty":39223,
    "event_date":"30 December 2017",
    "year":2017,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Chemical weapon",
    "actor1":"Military Forces of Syria (2000-)",
    "assoc_actor_1":"",
    "inter1":1,
    "actor2":"Civilians (Syria)",
    "assoc_actor_2":"",
    "inter2":7,
    "interaction":17,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Rural Damascus",
    "admin2":"Duma",
    "admin3":"Harasta",
    "location":"Misraba",
    "geo_precision":1,
    "source":"SNHR; Undisclosed Source",
    "source_scale":"Local partner-Other",
    "notes":"Syrian regime forces targeted with heavy artillery Misraba city in Rural Damascus province which killed one man. A chemical attack was reportedly carried out with no further fatalities reported.",
    "fatalities":1,
    "timestamp":1571164394,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 35.9212,33.3087 ]
    },
    "properties": {
    "data_id":6040340,
    "iso":760,
    "event_id_cnty":"SYR28723",
    "event_id_no_cnty":28723,
    "event_date":"15 November 2017",
    "year":2017,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Chemical weapon",
    "actor1":"Military Forces of Syria (2000-) Syrian Arab Air Force",
    "assoc_actor_1":"",
    "inter1":1,
    "actor2":"Civilians (Syria)",
    "assoc_actor_2":"",
    "inter2":7,
    "interaction":17,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Rural Damascus",
    "admin2":"Qatana",
    "admin3":"Bait Jan",
    "location":"Mazraet Beit Jin",
    "geo_precision":1,
    "source":"Liveuamap; SHAM",
    "source_scale":"Local partner-New media",
    "notes":"The Syrian army dropped barrel bombs suspected to contain a chemicals gases on Mazraet Beit Jin and Kafr Hoor towns in the Western Ghouta in Rural Damascus, where 3 suffocation cases were reported. No fatalities were reported.",
    "fatalities":0,
    "timestamp":1571164392,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 35.879,33.314 ]
    },
    "properties": {
    "data_id":5843587,
    "iso":760,
    "event_id_cnty":"SYR38420",
    "event_id_no_cnty":38420,
    "event_date":"20 October 2017",
    "year":2017,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Chemical weapon",
    "actor1":"Military Forces of Syria (2000-) Syrian Arab Air Force",
    "assoc_actor_1":"",
    "inter1":1,
    "actor2":"",
    "assoc_actor_2":"",
    "inter2":0,
    "interaction":10,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Rural Damascus",
    "admin2":"Qatana",
    "admin3":"Bait Jan",
    "location":"Bait Jan",
    "geo_precision":1,
    "source":"SHAM",
    "source_scale":"National",
    "notes":"Regime warplanes carried out Chlorine gas attacks on Beit Jan. No casualities were reported.",
    "fatalities":0,
    "timestamp":1567462249,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 35.9212,33.3087 ]
    },
    "properties": {
    "data_id":5841305,
    "iso":760,
    "event_id_cnty":"SYR40800",
    "event_id_no_cnty":40800,
    "event_date":"19 October 2017",
    "year":2017,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Chemical weapon",
    "actor1":"Military Forces of Syria (2000-) Syrian Arab Air Force",
    "assoc_actor_1":"",
    "inter1":1,
    "actor2":"",
    "assoc_actor_2":"",
    "inter2":0,
    "interaction":10,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Rural Damascus",
    "admin2":"Qatana",
    "admin3":"Bait Jan",
    "location":"Mazraet Beit Jin",
    "geo_precision":1,
    "source":"SHAM",
    "source_scale":"National",
    "notes":"Regime warplanes carried out Chlorine gas attacks on Mazraet Beit Jin town in Rural Damascus. No causalities were reported.",
    "fatalities":0,
    "timestamp":1567462246,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 36.0813,33.4387 ]
    },
    "properties": {
    "data_id":5906754,
    "iso":760,
    "event_id_cnty":"SYR14301",
    "event_id_no_cnty":14301,
    "event_date":"12 October 2017",
    "year":2017,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Chemical weapon",
    "actor1":"Military Forces of Syria (2000-) Syrian Arab Air Force",
    "assoc_actor_1":"",
    "inter1":1,
    "actor2":"",
    "assoc_actor_2":"",
    "inter2":0,
    "interaction":10,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Rural Damascus",
    "admin2":"Qatana",
    "admin3":"Qatana",
    "location":"Qatana",
    "geo_precision":2,
    "source":"SHAM; SOHR",
    "source_scale":"Other-National",
    "notes":"Suspected regime helicopters dropped barrel bombs on Tal Marwan in the Qatana district of Rural Damascus that reportedly contained chlorine gas. No injuries or fatalities reported.",
    "fatalities":0,
    "timestamp":1567462436,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 36.0813,33.4387 ]
    },
    "properties": {
    "data_id":5844640,
    "iso":760,
    "event_id_cnty":"SYR40439",
    "event_id_no_cnty":40439,
    "event_date":"12 October 2017",
    "year":2017,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Chemical weapon",
    "actor1":"Military Forces of Syria (2000-) Syrian Arab Air Force",
    "assoc_actor_1":"",
    "inter1":1,
    "actor2":"",
    "assoc_actor_2":"",
    "inter2":0,
    "interaction":10,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Rural Damascus",
    "admin2":"Qatana",
    "admin3":"Qatana",
    "location":"Qatana",
    "geo_precision":2,
    "source":"SHAM",
    "source_scale":"National",
    "notes":"Suspected regime helicopters dropped barrel bombs on Tal Marwan in the Qatana district of Rural Damascus that reportedly contained chlorine gas. No fatalities reported.",
    "fatalities":0,
    "timestamp":1567462250,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 35.9212,33.3087 ]
    },
    "properties": {
    "data_id":5841615,
    "iso":760,
    "event_id_cnty":"SYR38324",
    "event_id_no_cnty":38324,
    "event_date":"12 October 2017",
    "year":2017,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Chemical weapon",
    "actor1":"Military Forces of Syria (2000-) Syrian Arab Air Force",
    "assoc_actor_1":"",
    "inter1":1,
    "actor2":"",
    "assoc_actor_2":"",
    "inter2":0,
    "interaction":10,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Rural Damascus",
    "admin2":"Qatana",
    "admin3":"Bait Jan",
    "location":"Mazraet Beit Jin",
    "geo_precision":1,
    "source":"SHAM",
    "source_scale":"National",
    "notes":"Suspected regime helicopters dropped barrel bombs on Mazraet Bait Jan that reportedly contained chlorine gas. No fatalities reported.",
    "fatalities":0,
    "timestamp":1567462246,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 35.968,33.3083 ]
    },
    "properties": {
    "data_id":5842905,
    "iso":760,
    "event_id_cnty":"SYR40438",
    "event_id_no_cnty":40438,
    "event_date":"12 October 2017",
    "year":2017,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Chemical weapon",
    "actor1":"Military Forces of Syria (2000-) Syrian Arab Air Force",
    "assoc_actor_1":"",
    "inter1":1,
    "actor2":"",
    "assoc_actor_2":"",
    "inter2":0,
    "interaction":10,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Rural Damascus",
    "admin2":"Qatana",
    "admin3":"Bait Jan",
    "location":"Maghar Elmir",
    "geo_precision":1,
    "source":"SHAM",
    "source_scale":"National",
    "notes":"Suspected regime helicopters dropped barrel bombs on Maghar Elmir that reportedly contained chlorine gas. No fatalities reported.",
    "fatalities":0,
    "timestamp":1567462248,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 37.5253,35.0215 ]
    },
    "properties": {
    "data_id":6075996,
    "iso":760,
    "event_id_cnty":"SYR28226",
    "event_id_no_cnty":28226,
    "event_date":"07 October 2017",
    "year":2017,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Chemical weapon",
    "actor1":"Military Forces of Syria (2000-) Syrian Arab Air Force",
    "assoc_actor_1":"",
    "inter1":1,
    "actor2":"",
    "assoc_actor_2":"",
    "inter2":0,
    "interaction":10,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Hama",
    "admin2":"As-Salamiyeh",
    "admin3":"Oqeirbat",
    "location":"Msheirfeh",
    "geo_precision":1,
    "source":"Liveuamap",
    "source_scale":"Local partner-New media",
    "notes":"Regime helicopters dropped barrel bombs filled with chemical substance at Al-Musheirfeh village in Hama countryside. Neither injuries nor fatalities were reported.",
    "fatalities":0,
    "timestamp":1571164569,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 36.7197,34.73 ]
    },
    "properties": {
    "data_id":6082324,
    "iso":760,
    "event_id_cnty":"SYR27583",
    "event_id_no_cnty":27583,
    "event_date":"10 September 2017",
    "year":2017,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Chemical weapon",
    "actor1":"Unidentified Military Forces",
    "assoc_actor_1":"",
    "inter1":8,
    "actor2":"Sham Liberation Army",
    "assoc_actor_2":"",
    "inter2":2,
    "interaction":28,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Homs",
    "admin2":"Homs",
    "admin3":"Homs",
    "location":"Homs",
    "geo_precision":2,
    "source":"Liveuamap",
    "source_scale":"Local partner-New media",
    "notes":"Warplanes targeted the headquarters of Sham Liberation Army with toxic gases in the Syrian Badia. Neither injuries nor fatalities were reported.",
    "fatalities":0,
    "timestamp":1571164585,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 36.6353,35.929 ]
    },
    "properties": {
    "data_id":6036727,
    "iso":760,
    "event_id_cnty":"SYR11690",
    "event_id_no_cnty":11690,
    "event_date":"28 August 2017",
    "year":2017,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Chemical weapon",
    "actor1":"Unidentified Armed Group (Syria)",
    "assoc_actor_1":"",
    "inter1":3,
    "actor2":"",
    "assoc_actor_2":"",
    "inter2":0,
    "interaction":30,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Idleb",
    "admin2":"Idleb",
    "admin3":"Idleb",
    "location":"Idleb",
    "geo_precision":1,
    "source":"SOHR; Undisclosed Source",
    "source_scale":"Local partner-Other",
    "notes":"A gas IED device exploded in Idleb city. No fatalities reported.",
    "fatalities":0,
    "timestamp":1571164387,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 36.35,33.5134 ]
    },
    "properties": {
    "data_id":5841845,
    "iso":760,
    "event_id_cnty":"SYR40641",
    "event_id_no_cnty":40641,
    "event_date":"16 August 2017",
    "year":2017,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Chemical weapon",
    "actor1":"Military Forces of Syria (2000-)",
    "assoc_actor_1":"",
    "inter1":1,
    "actor2":"FaR: Al Rahman Corps",
    "assoc_actor_2":"",
    "inter2":2,
    "interaction":12,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Rural Damascus",
    "admin2":"Rural Damascus",
    "admin3":"Kafr Batna",
    "location":"Ein Terma",
    "geo_precision":1,
    "source":"SHAM",
    "source_scale":"National",
    "notes":"Syrian regime forces targeted FaR positions in Ein Tarma in Eastern Ghota using Chlorine that caused cases of suffocation symptoms among them. No fatalities reported.",
    "fatalities":0,
    "timestamp":1567462246,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 36.35,33.5134 ]
    },
    "properties": {
    "data_id":6082523,
    "iso":760,
    "event_id_cnty":"SYR26831",
    "event_id_no_cnty":26831,
    "event_date":"20 July 2017",
    "year":2017,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Chemical weapon",
    "actor1":"Military Forces of Syria (2000-)",
    "assoc_actor_1":"",
    "inter1":1,
    "actor2":"",
    "assoc_actor_2":"",
    "inter2":0,
    "interaction":10,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Rural Damascus",
    "admin2":"Rural Damascus",
    "admin3":"Kafr Batna",
    "location":"Ein Terma",
    "geo_precision":1,
    "source":"Liveuamap",
    "source_scale":"Local partner-New media",
    "notes":"Regime forces allegedly carried out chlorine attacks on areas in Ein Terma. No further indicaion concerning the type of attack. No deaths reported.",
    "fatalities":0,
    "timestamp":1571164585,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 36.35,33.5134 ]
    },
    "properties": {
    "data_id":6042518,
    "iso":760,
    "event_id_cnty":"SYR40519",
    "event_id_no_cnty":40519,
    "event_date":"14 July 2017",
    "year":2017,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Chemical weapon",
    "actor1":"Military Forces of Syria (2000-)",
    "assoc_actor_1":"Allied Syrian and/or Russian Forces",
    "inter1":1,
    "actor2":"Opposition Rebels (Syria)",
    "assoc_actor_2":"Civilians (Syria)",
    "inter2":2,
    "interaction":12,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Rural Damascus",
    "admin2":"Rural Damascus",
    "admin3":"Kafr Batna",
    "location":"Ein Terma",
    "geo_precision":1,
    "source":"SNHR; SHAM",
    "source_scale":"Local partner-Other",
    "notes":"Regime forces shelled Ein Terma town with toxic gas which resulted in suffocation sympotoms among the rebels and the civilians in the area. Jets, believed to be Syrian or Russian, bombarded and heavy shells fell on the area. 12 people were killed including children and women, and others were injured.",
    "fatalities":12,
    "timestamp":1571164394,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 36.3712,33.5643 ]
    },
    "properties": {
    "data_id":5842465,
    "iso":760,
    "event_id_cnty":"SYR40478",
    "event_id_no_cnty":40478,
    "event_date":"06 July 2017",
    "year":2017,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Chemical weapon",
    "actor1":"Unidentified Armed Group (Syria)",
    "assoc_actor_1":"",
    "inter1":3,
    "actor2":"Civilians (Syria)",
    "assoc_actor_2":"",
    "inter2":7,
    "interaction":37,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Rural Damascus",
    "admin2":"Duma",
    "admin3":"Harasta",
    "location":"Harasta",
    "geo_precision":1,
    "source":"SHAM",
    "source_scale":"National",
    "notes":"Heavy artillery shelling, by an unverified party, hit Harasta city which lead to many civilian injuries. Reports of Chlorine gas being used. No fatalities reported.",
    "fatalities":0,
    "timestamp":1567462247,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 36.4046,33.5706 ]
    },
    "properties": {
    "data_id":5841708,
    "iso":760,
    "event_id_cnty":"SYR37182",
    "event_id_no_cnty":37182,
    "event_date":"06 July 2017",
    "year":2017,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Chemical weapon",
    "actor1":"Unidentified Armed Group (Syria)",
    "assoc_actor_1":"",
    "inter1":3,
    "actor2":"Civilians (Syria)",
    "assoc_actor_2":"",
    "inter2":7,
    "interaction":37,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Rural Damascus",
    "admin2":"Duma",
    "admin3":"Duma",
    "location":"Duma",
    "geo_precision":1,
    "source":"SHAM",
    "source_scale":"National",
    "notes":"Heavy artillery shelling, by unverified party, on Duma city which lead to many injuries including between civilian population. Reports of Chlorine gas being used. No fatalities reported.",
    "fatalities":0,
    "timestamp":1567462246,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 36.3523,33.5284 ]
    },
    "properties": {
    "data_id":6049609,
    "iso":760,
    "event_id_cnty":"SYR8864",
    "event_id_no_cnty":8864,
    "event_date":"02 July 2017",
    "year":2017,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Chemical weapon",
    "actor1":"Military Forces of Syria (2000-)",
    "assoc_actor_1":"Allied Syrian and/or Russian Forces",
    "inter1":1,
    "actor2":"Civilians (Syria)",
    "assoc_actor_2":"",
    "inter2":7,
    "interaction":17,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Rural Damascus",
    "admin2":"Rural Damascus",
    "admin3":"Arbin",
    "location":"Zamalka",
    "geo_precision":1,
    "source":"Undisclosed Source; SOHR; SHAM",
    "source_scale":"Local partner-Other",
    "notes":"One man died affected by injuries he had in shelling carried out by the Syrian regime forces on Zamalka city in the Eastern Ghouta as warplanes that carried out three strikes the city. It was reported that regime forces shelled using Chlorine gas which lead to many cases of suffocation sympotoms.",
    "fatalities":1,
    "timestamp":1571164404,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 36.3523,33.5284 ]
    },
    "properties": {
    "data_id":6080683,
    "iso":760,
    "event_id_cnty":"SYR26604",
    "event_id_no_cnty":26604,
    "event_date":"02 July 2017",
    "year":2017,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Chemical weapon",
    "actor1":"Military Forces of Syria (2000-)",
    "assoc_actor_1":"",
    "inter1":1,
    "actor2":"FaR: Al Rahman Corps",
    "assoc_actor_2":"",
    "inter2":2,
    "interaction":12,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Rural Damascus",
    "admin2":"Rural Damascus",
    "admin3":"Arbin",
    "location":"Zamalka",
    "geo_precision":2,
    "source":"Liveuamap",
    "source_scale":"Local partner-New media",
    "notes":"Regime forces allegedly carried out chlorine attacks, by unknown means, on the Rahman Corps near Zamalka around Damascus. No deaths reported.",
    "fatalities":0,
    "timestamp":1571164583,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 36.421,33.5066 ]
    },
    "properties": {
    "data_id":6042427,
    "iso":760,
    "event_id_cnty":"SYR40105",
    "event_id_no_cnty":40105,
    "event_date":"18 May 2017",
    "year":2017,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Chemical weapon",
    "actor1":"Military Forces of Syria (2000-)",
    "assoc_actor_1":"",
    "inter1":1,
    "actor2":"",
    "assoc_actor_2":"",
    "inter2":0,
    "interaction":10,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Rural Damascus",
    "admin2":"Rural Damascus",
    "admin3":"Kafr Batna",
    "location":"Mahmadiyeh",
    "geo_precision":1,
    "source":"SHAM; Undisclosed Source",
    "source_scale":"Local partner-Other",
    "notes":"Suspected regime forces targeted fields in Mahmadiyeh in Rural Damascus province with 3 artillery shells and gas canister bombs. Neither injuries nor fatalities were reported.",
    "fatalities":0,
    "timestamp":1571164394,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 36.6633,35.2908 ]
    },
    "properties": {
    "data_id":5839628,
    "iso":760,
    "event_id_cnty":"SYR39922",
    "event_id_no_cnty":39922,
    "event_date":"30 April 2017",
    "year":2017,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Chemical weapon",
    "actor1":"Military Forces of Syria (2000-) Syrian Arab Air Force",
    "assoc_actor_1":"Military Forces of Syria (2000-)",
    "inter1":1,
    "actor2":"Civilians (Syria)",
    "assoc_actor_2":"",
    "inter2":7,
    "interaction":17,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Hama",
    "admin2":"Hama",
    "admin3":"Suran",
    "location":"Masasneh",
    "geo_precision":1,
    "source":"SHAM",
    "source_scale":"National",
    "notes":"Regime and Russian warplanes carried out tens of airstrikes on Almasasneh with rockets carrying poisonous gas in the northern countryside of Hama accompanied with artillery and rocket shelling. One fatality reported (coded at Lataminah) and several injuries.",
    "fatalities":0,
    "timestamp":1567462243,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 36.6204,35.3213 ]
    },
    "properties": {
    "data_id":6042400,
    "iso":760,
    "event_id_cnty":"SYR39921",
    "event_id_no_cnty":39921,
    "event_date":"30 April 2017",
    "year":2017,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Chemical weapon",
    "actor1":"Military Forces of Syria (2000-) Syrian Arab Air Force",
    "assoc_actor_1":"Military Forces of Syria (2000-)",
    "inter1":1,
    "actor2":"Civilians (Syria)",
    "assoc_actor_2":"",
    "inter2":7,
    "interaction":17,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Hama",
    "admin2":"Muhradah",
    "admin3":"Kafr Zeita",
    "location":"Al-Latamna",
    "geo_precision":1,
    "source":"SHAM; Liveuamap",
    "source_scale":"Local partner-New media",
    "notes":"Regime and Russian warplanes carried out tens of airstrikes on Al-Lataminah with rockets carrying poisonous gas in the northern countryside of Hama accompanied with artillery and rocket shelling. One fatality reported (coded at Lataminah) and several injuries.",
    "fatalities":1,
    "timestamp":1571164394,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 36.6204,35.3213 ]
    },
    "properties": {
    "data_id":6075482,
    "iso":760,
    "event_id_cnty":"SYR25385",
    "event_id_no_cnty":25385,
    "event_date":"29 April 2017",
    "year":2017,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Chemical weapon",
    "actor1":"Military Forces of Syria (2000-) Syrian Arab Air Force",
    "assoc_actor_1":"",
    "inter1":1,
    "actor2":"",
    "assoc_actor_2":"",
    "inter2":0,
    "interaction":10,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Hama",
    "admin2":"Muhradah",
    "admin3":"Kafr Zeita",
    "location":"Al-Latamna",
    "geo_precision":1,
    "source":"Liveuamap",
    "source_scale":"Local partner-New media",
    "notes":"A suspected Chlorine gas attack with barrel bombs was carried out by regime helicopters in Al-Lataminah city in northern Hama. Neither injuries nor fatalities were reported.",
    "fatalities":0,
    "timestamp":1571164569,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 36.3653,33.5388 ]
    },
    "properties": {
    "data_id":6082312,
    "iso":760,
    "event_id_cnty":"SYR25165",
    "event_id_no_cnty":25165,
    "event_date":"22 April 2017",
    "year":2017,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Chemical weapon",
    "actor1":"Unidentified Armed Group (Syria)",
    "assoc_actor_1":"",
    "inter1":3,
    "actor2":"Civilians (Syria)",
    "assoc_actor_2":"",
    "inter2":7,
    "interaction":37,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Rural Damascus",
    "admin2":"Rural Damascus",
    "admin3":"Arbin",
    "location":"Arbin",
    "geo_precision":1,
    "source":"Liveuamap",
    "source_scale":"Local partner-New media",
    "notes":"Suffocation cases have been reported in Arbin in Eastern Ghota Damascus. Neither injuries nor fatalities were reported.",
    "fatalities":0,
    "timestamp":1571164585,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 36.3523,33.5284 ]
    },
    "properties": {
    "data_id":6042390,
    "iso":760,
    "event_id_cnty":"SYR39835",
    "event_id_no_cnty":39835,
    "event_date":"22 April 2017",
    "year":2017,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Chemical weapon",
    "actor1":"Military Forces of Syria (2000-)",
    "assoc_actor_1":"",
    "inter1":1,
    "actor2":"Civilians (Syria)",
    "assoc_actor_2":"",
    "inter2":7,
    "interaction":17,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Rural Damascus",
    "admin2":"Rural Damascus",
    "admin3":"Arbin",
    "location":"Zamalka",
    "geo_precision":2,
    "source":"SHAM; Liveuamap",
    "source_scale":"Local partner-New media",
    "notes":"Regime forces targeted the area between Zamalka and Erbeen with hand-made bombs carrying poisonous chlorine gas, leading to some suffocations. Neither injuries nor fatalities reported.",
    "fatalities":0,
    "timestamp":1571164394,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 36.3524,33.5284 ]
    },
    "properties": {
    "data_id":6079848,
    "iso":760,
    "event_id_cnty":"SYR25188",
    "event_id_no_cnty":25188,
    "event_date":"22 April 2017",
    "year":2017,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Chemical weapon",
    "actor1":"Unidentified Armed Group (Syria)",
    "assoc_actor_1":"",
    "inter1":3,
    "actor2":"Civilians (Syria)",
    "assoc_actor_2":"",
    "inter2":7,
    "interaction":37,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Rural Damascus",
    "admin2":"Rural Damascus",
    "admin3":"Arbin",
    "location":"Zamalka",
    "geo_precision":1,
    "source":"Liveuamap",
    "source_scale":"Local partner-New media",
    "notes":"Suffocation cases have been reported in Zamalka in Eastern Ghota Damascus. Neither injuries nor fatalities were reported.",
    "fatalities":0,
    "timestamp":1571164582,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 36.5361,35.4395 ]
    },
    "properties": {
    "data_id":6123497,
    "iso":760,
    "event_id_cnty":"SYR43664",
    "event_id_no_cnty":43664,
    "event_date":"07 April 2017",
    "year":2017,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Chemical weapon",
    "actor1":"Military Forces of Syria (2000-)",
    "assoc_actor_1":"",
    "inter1":1,
    "actor2":"Civilians (Syria)",
    "assoc_actor_2":"",
    "inter2":7,
    "interaction":17,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Idleb",
    "admin2":"Al Ma'ra",
    "admin3":"Khan Shaykun",
    "location":"Al-Hibet",
    "geo_precision":1,
    "source":"SNHR",
    "source_scale":"Local partner-Other",
    "notes":"A civilian died after being exposed to poisonous gas used in an attack by regime forces on the town of Hbit in Idleb countryside.",
    "fatalities":1,
    "timestamp":1571164637,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 36.6504,35.4437 ]
    },
    "properties": {
    "data_id":6044842,
    "iso":760,
    "event_id_cnty":"SYR5130",
    "event_id_no_cnty":5130,
    "event_date":"04 April 2017",
    "year":2017,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Chemical weapon",
    "actor1":"Military Forces of Syria (2000-) Syrian Arab Air Force",
    "assoc_actor_1":"",
    "inter1":1,
    "actor2":"Civilians (Syria)",
    "assoc_actor_2":"",
    "inter2":7,
    "interaction":17,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Idleb",
    "admin2":"Al Ma'ra",
    "admin3":"Khan Shaykun",
    "location":"Khan Shaykun",
    "geo_precision":1,
    "source":"SOHR; SNHR",
    "source_scale":"Local partner-Other",
    "notes":"Syrian jets bombarded several areas in Khan Shaykun city in Idleb province, killing tens of civilians, including children and women and injuring more than 160 others. Cases of suffocation, as a result of chemical weapons, were confirmed by medical sources. Later reports confirmed 88 fatalities.",
    "fatalities":88,
    "timestamp":1571164398,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 36.7613,35.1337 ]
    },
    "properties": {
    "data_id":5844485,
    "iso":760,
    "event_id_cnty":"SYR39719",
    "event_id_no_cnty":39719,
    "event_date":"30 March 2017",
    "year":2017,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Chemical weapon",
    "actor1":"Unidentified Military Forces",
    "assoc_actor_1":"",
    "inter1":8,
    "actor2":"Opposition Rebels (Syria)",
    "assoc_actor_2":"Civilians (Syria)",
    "inter2":2,
    "interaction":28,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Hama",
    "admin2":"Hama",
    "admin3":"Hama",
    "location":"Hama",
    "geo_precision":3,
    "source":"SHAM",
    "source_scale":"National",
    "notes":"Warplanes targeted Al-Zuwar town in Hama with toxic gases, which caused 20 cases of suffocation among civilians and rebels. No fatalities were reported.",
    "fatalities":0,
    "timestamp":1567462250,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 36.6204,35.3213 ]
    },
    "properties": {
    "data_id":5910972,
    "iso":760,
    "event_id_cnty":"SYR4832",
    "event_id_no_cnty":4832,
    "event_date":"30 March 2017",
    "year":2017,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Chemical weapon",
    "actor1":"Unidentified Military Forces",
    "assoc_actor_1":"",
    "inter1":8,
    "actor2":"Opposition Rebels (Syria)",
    "assoc_actor_2":"Civilians (Syria)",
    "inter2":2,
    "interaction":28,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Hama",
    "admin2":"Muhradah",
    "admin3":"Kafr Zeita",
    "location":"Al-Latamna",
    "geo_precision":1,
    "source":"SOHR; SHAM",
    "source_scale":"Other-National",
    "notes":"Warplanes targeted Al-Latamna city in Hama with toxic gases, which caused 20 cases of suffocation among civilians and rebels. It was also reported that the warplanes' raids on Latamina, Arza, Zowar, and Qamhana which are controlled by rebel forces, lead to 50 civilians experincing suffocation symptoms. Fatalities also reported with the unknown number coded as 10.",
    "fatalities":10,
    "timestamp":1567462442,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 36.6204,35.3213 ]
    },
    "properties": {
    "data_id":6043717,
    "iso":760,
    "event_id_cnty":"SYR4675",
    "event_id_no_cnty":4675,
    "event_date":"26 March 2017",
    "year":2017,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Chemical weapon",
    "actor1":"Military Forces of Syria (2000-) Syrian Arab Air Force",
    "assoc_actor_1":"",
    "inter1":1,
    "actor2":"Civilians (Syria)",
    "assoc_actor_2":"",
    "inter2":7,
    "interaction":17,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Hama",
    "admin2":"Muhradah",
    "admin3":"Kafr Zeita",
    "location":"Al-Latamna",
    "geo_precision":1,
    "source":"Liveuamap; SOHR; SHAM",
    "source_scale":"Local partner-New media",
    "notes":"Regime warplanes and helicopters targeted Al-Latamna city in Hama. The city was targeted with chlorine gas, which caused suffocation symptoms among civilians. No fatalities reported.",
    "fatalities":0,
    "timestamp":1571164396,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 36.6204,35.3213 ]
    },
    "properties": {
    "data_id":6043593,
    "iso":760,
    "event_id_cnty":"SYR4624",
    "event_id_no_cnty":4624,
    "event_date":"25 March 2017",
    "year":2017,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Chemical weapon",
    "actor1":"Military Forces of Syria (2000-) Syrian Arab Air Force",
    "assoc_actor_1":"Military Forces of Russia (2000-)",
    "inter1":1,
    "actor2":"Civilians (Syria)",
    "assoc_actor_2":"Health Workers (Syria)",
    "inter2":7,
    "interaction":17,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Hama",
    "admin2":"Muhradah",
    "admin3":"Kafr Zeita",
    "location":"Al-Latamna",
    "geo_precision":1,
    "source":"SNHR; SOHR; SHAM",
    "source_scale":"Local partner-Other",
    "notes":"Russian and Syrian warplanes and helicopters targeted Al-Latamna city in Hama. The city was targeted with barrel bombs which contained chlorine gas, that killed a doctor and caused other cases of suffocations.",
    "fatalities":1,
    "timestamp":1571164396,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 36.3712,33.5643 ]
    },
    "properties": {
    "data_id":5858088,
    "iso":760,
    "event_id_cnty":"SYR3393",
    "event_id_no_cnty":3393,
    "event_date":"27 February 2017",
    "year":2017,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Chemical weapon",
    "actor1":"Military Forces of Syria (2000-) Syrian Arab Air Force",
    "assoc_actor_1":"",
    "inter1":1,
    "actor2":"Civilians (Syria)",
    "assoc_actor_2":"",
    "inter2":7,
    "interaction":17,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Rural Damascus",
    "admin2":"Duma",
    "admin3":"Harasta",
    "location":"Harasta",
    "geo_precision":1,
    "source":"SOHR",
    "source_scale":"Other",
    "notes":"Regime warplanes carried out shortly before midnight yesterday raids on places in Harasta area west of the International highway in the Eastern Ghouta, which resulted in the outbreak of fire in the area. Later reports confirm the use of gas killing 15 people.",
    "fatalities":15,
    "timestamp":1567462267,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 36.3712,33.5643 ]
    },
    "properties": {
    "data_id":6039712,
    "iso":760,
    "event_id_cnty":"SYR24143",
    "event_id_no_cnty":24143,
    "event_date":"26 February 2017",
    "year":2017,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Chemical weapon",
    "actor1":"Military Forces of Syria (2000-)",
    "assoc_actor_1":"",
    "inter1":1,
    "actor2":"Civilians (Syria)",
    "assoc_actor_2":"",
    "inter2":7,
    "interaction":17,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Rural Damascus",
    "admin2":"Duma",
    "admin3":"Harasta",
    "location":"Harasta",
    "geo_precision":1,
    "source":"Liveuamap; SHAM; SNHR",
    "source_scale":"Local partner-Other",
    "notes":"Regime forces shelled Harasta city with what is believed to be toxic gas. As a result, many civilians experienced suffocation symptoms, and it was reported that 1 civilian died.",
    "fatalities":1,
    "timestamp":1571164391,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 36.46,33.5472 ]
    },
    "properties": {
    "data_id":5840942,
    "iso":760,
    "event_id_cnty":"SYR39536",
    "event_id_no_cnty":39536,
    "event_date":"21 February 2017",
    "year":2017,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Chemical weapon",
    "actor1":"Military Forces of Syria (2000-)",
    "assoc_actor_1":"",
    "inter1":1,
    "actor2":"Opposition Rebels (Syria)",
    "assoc_actor_2":"Civilians (Syria)",
    "inter2":2,
    "interaction":12,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Rural Damascus",
    "admin2":"Duma",
    "admin3":"Duma",
    "location":"Hosh al-Dawahira",
    "geo_precision":1,
    "source":"SHAM",
    "source_scale":"National",
    "notes":"Syrian regime forces targeted Hosh Al-Dawahira town in Rural Damascus with Chlorine gas rockets which caused suffocations amongst civilians and rebels. No fatalities reported.",
    "fatalities":0,
    "timestamp":1567462245,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 36.3653,33.5388 ]
    },
    "properties": {
    "data_id":6081378,
    "iso":760,
    "event_id_cnty":"SYR24000",
    "event_id_no_cnty":24000,
    "event_date":"21 February 2017",
    "year":2017,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Chemical weapon",
    "actor1":"Military Forces of Iran (1989-)",
    "assoc_actor_1":"",
    "inter1":8,
    "actor2":"",
    "assoc_actor_2":"",
    "inter2":0,
    "interaction":80,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Rural Damascus",
    "admin2":"Rural Damascus",
    "admin3":"Arbin",
    "location":"Arbin",
    "geo_precision":2,
    "source":"Liveuamap",
    "source_scale":"Local partner-New media",
    "notes":"Iranian Forces shelled Eastern Ghouta area around Arbin with Iranian IRAM claimed to contain chlorine gas. No information about casualties.",
    "fatalities":0,
    "timestamp":1571164584,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 36.3653,33.5388 ]
    },
    "properties": {
    "data_id":6078830,
    "iso":760,
    "event_id_cnty":"SYR23728",
    "event_id_no_cnty":23728,
    "event_date":"09 February 2017",
    "year":2017,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Chemical weapon",
    "actor1":"Militia (Pro-Government)",
    "assoc_actor_1":"",
    "inter1":3,
    "actor2":"Civilians (Syria)",
    "assoc_actor_2":"",
    "inter2":7,
    "interaction":37,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Rural Damascus",
    "admin2":"Rural Damascus",
    "admin3":"Arbin",
    "location":"Arbin",
    "geo_precision":2,
    "source":"Liveuamap",
    "source_scale":"Local partner-New media",
    "notes":"A chlorine gas attack, suspected to have been lunched by Pro-Government militias, was reported in Eastern Ghouta around Arbin city, with information about one fatality and other casualties.",
    "fatalities":1,
    "timestamp":1571164580,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 36.1979,33.604 ]
    },
    "properties": {
    "data_id":5840116,
    "iso":760,
    "event_id_cnty":"SYR39288",
    "event_id_no_cnty":39288,
    "event_date":"05 January 2017",
    "year":2017,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Chemical weapon",
    "actor1":"Military Forces of Syria (2000-)",
    "assoc_actor_1":"",
    "inter1":1,
    "actor2":"Civilians (Syria)",
    "assoc_actor_2":"",
    "inter2":7,
    "interaction":17,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Rural Damascus",
    "admin2":"Rural Damascus",
    "admin3":"Qudsiya",
    "location":"Basimah",
    "geo_precision":1,
    "source":"SHAM",
    "source_scale":"National",
    "notes":"Syrian regime forces targeted Basimah village in Rural Damascus using Chlorine gas which caused cases of suffocation among people. Neither injuries nor fatalities were reported.",
    "fatalities":0,
    "timestamp":1567462244,
    "iso3":"SYR"
    }
  }
]
}